Repository Dream-Home-PEABOT/BEE_DreamHome, pull requests merged in 2021-01, with the labels that each got.

#13 Readme
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  dreamhome.py
Labels: reviewer left comments

#27 Education
  .circleci/config.yml
  README.md
  api/models/education.py
  mvc.md
Labels: backend

#29 Education endpoints
  .gitignore
  api/controller/EducationController.py
  api/controller/education/.keep
  api/models/education.py
  api/routes/api_routes.py
  api/views/education_documentation.html
  dreamhome.py
Labels: backend

#41 Education error
  api/controller/EducationController.py
  api/controller/ReportController_comingsoon.py
  api/helpers/errors.py
  dreamhome.py
  tests/BaseCase.py
  tests/test_education_crud_sad_paths.py
Labels: backend

#40 Initial deployment
  .keep
  database/education.json
  requirements.txt
Labels: backend

#45 Property taxes
  .vscode/settings.json
  Pipfile
  Pipfile.lock
  api/controller/EducationController.py
  api/controller/PropertyTaxController.py
  api/models/property_tax.py
  api/routes/api_routes.py
  database/property_tax.py
  tests/test_property_tax_crud.py
Labels: backend

#51 Pmi
  api/controller/PmiController.py
  api/models/pmi.py
  api/models/report_comingsoon.py
  api/routes/api_routes.py
  database/pmi.py
  pmi.md
  tests/test_pmi_crud.py
Labels: backend

#54 Sad paths
  api/controller/EducationController.py
  api/controller/HomeInsuranceController.py
  api/controller/PmiController.py
  api/controller/PropertyTaxController.py
  api/controller/ReportController.py
  api/models/home_insurance.py
  api/routes/api_routes.py
  database/insurance.py
  tests/test_education_crud.py
  tests/test_home_insurance_crud.py
  tests/test_home_insurance_sad_paths.py
  tests/test_pmi_crud.py
  tests/test_pmi_sad_path.py
  tests/test_property_tax_crud.py
  tests/test_property_tax_sad_path.py
Labels: backend

#55 Report sad path
  api/controller/EducationController.py
  api/controller/HomeInsuranceController.py
  api/controller/PmiController.py
  api/controller/PropertyTaxController.py
  api/controller/ReportController.py
  api/models/report.py
  app.py
  database/report.py
  tests/test_education_crud.py
  tests/test_home_insurance_crud.py
  tests/test_pmi_crud.py
  tests/test_property_tax_crud.py
  tests/test_report_crud.py
  tests/test_report_sad_path.py
Labels: backend

#56 Report model update
  api/controller/ReportController.py
  api/controller/ReportController_comingsoon.py
  api/helpers/errors.py
  api/models/report.py
  api/models/report_comingsoon.py
Labels: backend

#57 Development2
  .keep
  api/controller/EducationController.py
  api/controller/HomeInsuranceController.py
  api/controller/PmiController.py
  api/controller/PropertyTaxController.py
  api/controller/ReportController.py
  api/controller/ReportController_comingsoon.py
  api/helpers/errors.py
  api/models/report.py
  api/models/report_comingsoon.py
  app.py
  database/report.py
  tests/test_education_crud.py
  tests/test_home_insurance_crud.py
  tests/test_pmi_crud.py
  tests/test_property_tax_crud.py
  tests/test_report_crud.py
  tests/test_report_sad_path.py
Labels: backend

#60 Add a final readme for mvp
  README.md
Labels: backend

#83 It1 update report model
  api/controller/EducationController.py
  api/controller/ReportController.py
  api/models/education.py
  api/models/report.py
  database/education.py
  database/it1_education.json
  database/it1_report.json
  database/report.py
Labels: backend

#85 External API Consumption for Zipcode to Location
  Pipfile
  Pipfile.lock
  api/models/report.py
  api/services/zip.py
  app.py
  requirements.txt
Labels: backend

#91 Mortgage rate
  api/controller/MortgageRateController.py
  api/models/mortgage_rate.py
  api/routes/api_routes.py
  database/mortgage_rate.py
  tests/test_mortgage_rate_crud.py
Labels: backend

#93 Typos
  .vscode/settings.json
  api/controller/MortgageRateController.py
  api/models/mortgage_rate.py
  database/mortgage_rate.py
  tests/test_mortgage_rate_crud.py
Labels: backend

#94 Circle ci Setup
  .circleci/config.yml
  app.py
Labels: backend

#96 Seeds
  README.md
  api/controller/HomeInsuranceController.py
  api/controller/PropertyTaxController.py
  api/models/home_insurance.py
  api/models/property_tax.py
  database/home_insurance.py
  database/insurance.py
  database/property_tax.py
  tests/test_home_insurance_crud.py
  tests/test_home_insurance_sad_paths.py
  tests/test_pmi_sad_path.py
  tests/test_property_tax_crud.py
  tests/test_property_tax_sad_path.py
Labels: backend

#97 Iteration 1 Updates to Report and Controller
  api/controller/EducationController.py
  api/controller/ReportController.py
  api/services/zip.py
  app.py
  database/report.py
  tests/test_education_crud.py
  tests/test_education_crud_sad_paths.py
  tests/test_home_insurance_crud.py
  tests/test_home_insurance_sad_paths.py
  tests/test_mortgage_rate_crud.py
  tests/test_pmi_crud.py
  tests/test_pmi_sad_path.py
  tests/test_property_tax_crud.py
  tests/test_property_tax_sad_path.py
  tests/test_report_crud.py
  tests/test_report_model_functions.py
  tests/test_report_sad_path.py
  tests/test_welcome.py
Labels: backend

#101 Auth addition
  api/controller/ReportController.py
  api/models/report.py
  api/routes/api_routes.py
  api/services/zip.py
  database/report.py
  tests/test_authorization.py
  tests/test_report_crud.py
Labels: backend

#102 It1 update to report
  api/controller/HomeInsuranceController.py
  api/controller/MortgageRateController.py
  api/controller/PropertyTaxController.py
  api/controller/ReportController.py
  api/helpers/state_abbrev_to_full.py
  api/models/report.py
  api/routes/api_routes.py
  api/services/zip.py
  database/home_insurance.py
  database/property_tax.py
  tests/BaseCase.py
  tests/test_authorization.py
  tests/test_home_insurance_crud.py
  tests/test_home_insurance_sad_paths.py
  tests/test_mortgage_rate_crud.py
  tests/test_property_tax_crud.py
  tests/test_property_tax_sad_path.py
  tests/test_report_crud.py
Labels: backend

#104 Zip Code to Average Home Price
  api/controller/MedianHomeValueController.py
  api/controller/ReportController.py
  api/models/median_home_value.py
  api/models/report.py
  api/routes/api_routes.py
  api/services/zip.py
  database/median_home_value.py
  tests/BaseCase.py
  tests/test_authorization.py
  tests/test_median_home_value_crud.py
  tests/test_report_crud.py
Labels: backend

#105 It1 dev2
  api/controller/HomeInsuranceController.py
  api/controller/MedianHomeValueController.py
  api/controller/MortgageRateController.py
  api/controller/PropertyTaxController.py
  api/controller/ReportController.py
  api/helpers/state_abbrev_to_full.py
  api/models/median_home_value.py
  api/models/report.py
  api/routes/api_routes.py
  api/services/zip.py
  database/home_insurance.py
  database/median_home_value.py
  database/property_tax.py
  database/report.py
  tests/BaseCase.py
  tests/test_authorization.py
  tests/test_home_insurance_crud.py
  tests/test_home_insurance_sad_paths.py
  tests/test_median_home_value_crud.py
  tests/test_mortgage_rate_crud.py
  tests/test_property_tax_crud.py
  tests/test_property_tax_sad_path.py
  tests/test_report_crud.py
Labels: backend

#107 Bug fix
  api/controller/ReportController.py
  api/models/report.py
  requirements.txt
  tests/BaseCase.py
  tests/test_authorization.py
  tests/test_median_home_value_crud.py
  tests/test_report_crud.py
Labels: backend, bug, bug fixed

#108 All seeds added and verified
  database/median_home_value.py
Labels: backend

#110 Debug Get Report ID and Get Report by UID
  api/controller/ReportController.py
  api/models/report.py
Labels: backend, bug, bug fixed

#112 Convert report/unique from GET to POST
  api/routes/api_routes.py
Labels: backend, bug, bug fixed

#113 Report refactor cont
  api/models/report.py
  tests/test_authorization.py
Labels: backend, bug, bug fixed

#114 Add functionality for downpayment_cash_value to Report
  api/controller/ReportController.py
  api/models/report.py
Labels: backend
